# Generated by Django 5.1.4 on 2025-01-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0003_remove_servicerequest_status_changed_by_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
