# Generated by Django 5.1.4 on 2025-01-16 12:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0008_alter_announcement_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
