# Generated by Django 5.1.4 on 2025-01-16 12:21

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0009_alter_newsfeed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeed',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
