# Generated by Django 5.1.4 on 2025-01-16 17:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0010_alter_newsfeed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialfile',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='file'),
        ),
    ]
