# Generated by Django 5.1.4 on 2025-01-24 07:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0012_emergencyhotline_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='proof_of_membership',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='membership_proof'),
            preserve_default=False,
        ),
    ]
