# Generated by Django 5.1.4 on 2025-01-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0013_user_proof_of_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='vehicles_owned',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
