# Generated by Django 5.1.4 on 2025-01-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0014_alter_household_vehicles_owned'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='street',
            field=models.CharField(choices=[('Bellflower', 'Bellflower'), ('Carnation', 'Carnation'), ('Dahlia', 'Dahlia'), ('Daisy', 'Daisy'), ('Gardenia', 'Gardenia'), ('Hyacinth', 'Hyacinth'), ('Petunia', 'Petunia'), ('Poinsettia', 'Poinsettia'), ('Primrose', 'Primrose')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
