# Generated by Django 5.1.4 on 2025-01-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0016_grievanceappointment_certification_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='grievanceappointment',
            name='purpose',
            field=models.CharField(blank=True, choices=[('Homeowners Certificate', 'Homeowners Certificate'), ('Move In / Move Out', 'Move In / Move Out'), ('Gate Pass', 'Gate Pass'), ('Business Permit (New/Renewal)', 'Business Permit (New/Renewal)'), ('Building Permit (Renovation/Extension/Fence)', 'Building Permit (Renovation/Extension/Fence)'), ('Employment/Loan/School/Police Clearance/ID', 'Employment/Loan/School/Police Clearance/ID'), ('Car Sticker', 'Car Sticker'), ('Other', 'Other Purpose (Specify)')], max_length=50, null=True),
        ),
    ]
