# Generated by Django 5.1.4 on 2025-01-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0020_remove_electionsession_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionsession',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='electionsession',
            name='start_date',
            field=models.DateField(),
        ),
    ]
