# Generated by Django 5.1.4 on 2025-01-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SVG2', '0021_alter_electionsession_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionsession',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
